version: '3.8'

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3000:5173'
        volumes:
            - /app/node_modules
            - ./:/app
